name: iOS Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
      
      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          pod install

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.2'

      - name: Clean build folder
        run: xcodebuild clean -project RickMorty.xcodeproj -scheme RickMorty -configuration Release

      - name: Build the app
        run: xcodebuild build -project RickMorty.xcodeproj -scheme RickMorty -configuration Release
